name: Release

on:
  push:
    tags:
      - 'v*'

# GitHub Actions permissions
permissions:
  contents: write
  packages: write

jobs:
  # Windows Build
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build React app
      run: npm run build
      
    - name: Build Windows app
      run: npm run build:win
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        CI: true
        
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: release/*.exe

  # macOS Build
  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build React app
      run: npm run build
      
    - name: Build macOS app (with ad-hoc signing)
      run: npm run build:mac
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        CI: true
        CSC_IDENTITY_AUTO_DISCOVERY: false
        CREATE_DMG_WITH_AD_HOC_SIGN: true
        
    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: release/*.dmg

  # Linux Build
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build React app
      run: npm run build
      
    - name: Build Linux app
      run: npm run build:linux
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        CI: true
        
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: release/*.AppImage

  # Create Release
  release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download Windows build
      uses: actions/download-artifact@v4
      with:
        name: windows-build
        path: release/
        
    - name: Download macOS build
      uses: actions/download-artifact@v4
      with:
        name: macos-build
        path: release/
        
    - name: Download Linux build
      uses: actions/download-artifact@v4
      with:
        name: linux-build
        path: release/
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          release/*.exe
          release/*.dmg
          release/*.AppImage
        body_path: CHANGELOG.md
        draft: false
        prerelease: false
        make_latest: true
        fail_on_unmatched_files: false
        token: ${{ secrets.GH_TOKEN }}